# Default values for api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
buildID: "tbc"

projects:
  imageVersion: 0.3.2

rabbitmq:
  extraConfiguration: |-
    management.path_prefix = /mqadmin/
  ingress:
    enabled: false    
  auth:
    username: "jpp"
    password: "jpp"
  persistence:
    enabled: false
  livenessProbe:
    enabled: false
  readinessProbe:
    enabled: false
  