# Default values for api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
buildID: "tbc"

rabbitmq:
  extraConfiguration: |-
    management.path_prefix = /mqadmin/
  ingress:
    enabled: false    
  auth:
    username: "jpp"
    password: "jpp"
  persistence:
    enabled: false
  livenessProbe:
    enabled: false
  readinessProbe:
    enabled: false
    
traefik:
  ports:
    amqp:
      port: 8672
      # hostPort: 8443
      expose: true
      exposedPort: 5672
      # The port protocol (TCP/UDP)
      protocol: TCP
      # nodePort: 32443
  nodeSelector:      
    node-role.kubernetes.io/master: "true"
  