apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: main-gateway
  namespace: istio-system
spec:
  gatewayClassName: istio
  listeners:  
  - protocol: HTTP
    port: 80
    name: httpin
    allowedRoutes:
      namespaces:
        from: All
  - protocol: HTTP
    port: 5341
    name: seqingestin
    allowedRoutes:
      namespaces:
        from: All
  - protocol: TCP
    port: 5432
    name: postgresql
    allowedRoutes:
      namespaces:
        from: All
  - name: https
    hostname: "services.cedarbarn.local"
    port: 443
    protocol: HTTPS
    tls:
      mode: Terminate
      certificateRefs:
      - name: sslcert
    allowedRoutes:
      namespaces:        
        from: All
  - name: subhttps
    hostname: "*.services.cedarbarn.local"
    port: 443
    protocol: HTTPS
    tls:
      mode: Terminate
      certificateRefs:
      - name: wildcardsslcert
    allowedRoutes:
      namespaces:        
        from: All