apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: kiali
  namespace: istio-system
spec:
  interval: 60m0s
  url: https://kiali.org/helm-charts
---  
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kiali
  namespace: istio-system
spec:
  chart:
    spec:
      chart: kiali-server
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: kiali
      version: ">=0.0.0"
  values:
    auth:
      strategy: "anonymous"
  interval: 5m0s
  dependsOn: 
    - name: istiod