apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: jppcorerepo
  namespace: default
spec:
  type: oci
  interval: 5m0s
  url: oci://ghcr.io/jppgroup
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jppcore
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: localcluster
      version: '>=0.3.4'
      sourceRef:
        kind: HelmRepository
        name: jppcorerepo
        namespace: default
      interval: 5m
  install:
    remediation:
      retries: 2
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true
  dependsOn:
    - name: traefik
  values:
    projects:
      imageVersion: 0.4.2
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: projectroute
  namespace: default
spec:
  parentRefs:
  - name: main-gateway
    sectionName: httpin
    namespace: istio-system
  hostnames:
  - "services.cedarbarn.local"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /projects    
    filters:
    - type: URLRewrite
      urlRewrite:          
        path:
          type: ReplacePrefixMatch
          #replacePrefixMatch: /fennel
    backendRefs:
    - name: projects
      port: 80