apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: postgresqlrepo
  namespace: default
spec:  
  interval: 5m0s
  url: https://charts.bitnami.com/bitnami
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgresql
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: postgresql
      version: '13.*'
      sourceRef:
        kind: HelmRepository
        name: postgresqlrepo
        namespace: default
      interval: 5m
  install:
    crds: CreateReplace
    remediation:
      retries: 2
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
      remediateLastFailure: true
  values:
    global:
      postgresql:
        auth:
          postgresPassword: Is92n$8&z^EI
          username: aspnetuser
          password: Wh97G@3!pCeA
          database: aspnet-ProjectManager
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: postgresqlroute
  namespace: default
spec:
  parentRefs:
  - name: main-gateway
    sectionName: postgresql
    namespace: istio-system  
  rules:
  - backendRefs:
    - name: postgresql
      port: 5432
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: postgresqlbackup
  namespace: default
spec:
  schedule: "30 18 * * 0-5"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: dbbackup
            image: ghcr.io/jppgroup/dbbackup:1.0.0
            imagePullPolicy: IfNotPresent          
            env:
            - name: PGPASSWORD
              value: "Is92n$8&z^EI"
            - name: PGPORT
              value: "5432"  
            - name: PGHOST
              value: "postgresql"  
            - name: CONTAINER
              value: "https://jppcdnstorage.blob.core.windows.net/backups?sv=2021-10-04&st=2023-10-29T22%3A33%3A04Z&se=2033-10-30T22%3A33%3A00Z&sr=c&sp=racwl&sig=P%2BBJoo8t98CDCU8TuxkXUFJhatYNqckvxw4y7v%2FafNI%3D"  
          restartPolicy: Never