apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jpppm
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: jppprojectmanager
      version: '>=0.3.0'
      sourceRef:
        kind: HelmRepository
        name: jpphelmrepo
        namespace: default
      interval: 5m
  install:
    remediation:
      retries: 2
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true
  dependsOn:
    - name: postgresql
  values:
    projectmanager:
      imageVersion: 0.2.0
      databaseaddress: postgresql
    gateway:
      enable: true
    global:
      postgresql:
        auth: 
          password: Wh97G@3!pCeA