apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: seqrepo
  namespace: default
spec:
  interval: 5m0s
  url: https://helm.datalust.co
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: seq
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: seq
      version: '>=2022.1.0'
      sourceRef:
        kind: HelmRepository
        name: seqrepo
        namespace: default
      interval: 5m
  install:
    remediation:
      retries: 2
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true  
  values:
    ui:
      ingress:
        annotations:
          kubernetes.io/ingress.class: traefik    
        enabled: true
        path: /
        hosts:
          - 'seq.services.cedarbarn.local'
      
    ingestion:
      ingress:
        annotations:
          kubernetes.io/ingress.class: traefik
        enabled: true
        path: /
        hosts:
          - 'seq.services.cedarbarn.local'
  
    persistence:
      storageClass: local-path
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: seqroute
  namespace: default
spec:
  parentRefs:
  - name: main-gateway
    sectionName: httpin
    namespace: istio-system
  hostnames:
  - "seq.services.cedarbarn.local"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /    
    backendRefs:
    - name: seq
      port: 80
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: seqadminroute
  namespace: default
spec:
  parentRefs:
  - name: main-gateway
    sectionName: seqingestin
    namespace: istio-system
  hostnames:
  - "seqingest.services.cedarbarn.local"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /    
    backendRefs:
    - name: seq
      port: 5341