apiVersion: apps/v1
kind: Deployment
metadata:
  name: projects  
spec:
  replicas: 2
  selector:
    matchLabels:
      app: projects
  template:
    metadata:
      labels:
        app: projects
    spec:
      containers:
      - name: projects       
        image: ghcr.io/jppgroup/projects:0.1.6
        args: ["run"]
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /health
            port: 80                      
          periodSeconds: 15
          initialDelaySeconds: 15
        resources:
          requests:
            memory: "256M"
            cpu: "0.25"
          limits:
            memory: "512M"
            cpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: projects
spec:
  selector:
    app: projects
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
kind: IngressRoute
apiVersion: traefik.containo.us/v1alpha1
metadata:
  name: projects-ingress
  namespace: default
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: PathPrefix(`/projects/`)  
      middlewares:                    
      - name: projects-ingress-prefixstrip   
      services:
        - kind: Service
          name: projects
          namespace: default
          port: 80
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: projects-ingress-prefixstrip 
spec:
  stripPrefix:
    prefixes:
      - /projects/   
          