apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: jppcorerepo
  namespace: default
spec:
  type: oci
  interval: 5m0s
  url: oci://ghcr.io/jppgroup
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jppcore
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: localcluster
      version: '>=0.3.0'
      sourceRef:
        kind: HelmRepository
        name: jppcorerepo
        namespace: default
      interval: 5m
  install:
    remediation:
      retries: 2
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true
  dependsOn:
    - name: traefik
  values:
    replicaCount: 2