apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jppls
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: jpplicensescanner
      version: '>=0.1.0'
      sourceRef:
        kind: HelmRepository
        name: jpphelmrepo
        namespace: default
      interval: 5m
  install:
    remediation:
      retries: 2
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true
  dependsOn:
    - name: postgresql
  values:
    licensescanner:
      imageVersion: 0.1.1
      databaseaddress: postgresql
    global:
      postgresql:
        auth: 
          password: Wh97G@3!pCeA