apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: traefikrepo
  namespace: default
spec:  
  interval: 5m0s
  url: https://helm.traefik.io/traefik
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: traefik
      version: '>10.0.0'
      sourceRef:
        kind: HelmRepository
        name: traefikrepo
        namespace: default
      interval: 5m
  values:
    ports:
      amqp:
        port: 8672
        # hostPort: 8443
        expose: true
        exposedPort: 5672
        # The port protocol (TCP/UDP)
        protocol: TCP
        # nodePort: 32443
    nodeSelector:      
      node-role.kubernetes.io/master: "true"
  