name: Start AKS Cloud Cluster
on:
  schedule:
    - cron: '30 18 * * 1-5'
  workflow_dispatch:

jobs:
  Start:
    runs-on: ubuntu-latest
    steps:      
      - name: Log in with Azure
        uses: azure/login@v1
        with:
          creds: '${{ secrets.AKSCLOUDCRED }}'
      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          azcliversion: 2.30.0
          inlineScript: |
            az aks stop --name Cloud --resource-group CloudCluster